language: node_js
node_js:
  - 12

services:
  - docker

branches:
  only:
    - master

  #Pre-testing installs
install:
  - npm install
  - npm run build

#script to be run such as tests

before_script:
  - echo "no tests"

script:
  - docker --version #print docker version
  - docker build -t feed-api .
  - docker tag feed-api waqasnoor/feed-api:latest
  - docker tag feed-api waqasnoor/feed-api:"$TRAVIS_BUILD_NUMBER"

# Tasks to perform after image
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push waqasnoor/feed-api:"$TRAVIS_BUILD_NUMBER"
  - docker push waqasnoor/feed-api:latest
